#!/bin/zsh
# Setup neovim

. $DOT/utils/print_functions.sh

info "Setup Neovim"

rm -rf $CONFIG/nvim

if ln -sf $DOT/nvim/config $CONFIG/nvim > /dev/null ; then
  success "Config Files Linked"
else
  fail "Error on Linking Files"
fi
