#!/bin/zsh
# Setup neovim

. $DOT/utils/print_functions.sh

info "Setup Neovim"

mkdir -p $CONFIG/nvim > /dev/null


if ln -sf $DOT/nvim/config/* $CONFIG/nvim > /dev/null \
&& ln -sf $DOT/nvim/config/.* $CONFIG/nvim > /dev/null; then
  success "Config Files Linked"
else
  fail "Error on Linking Files"
fi
