#!/bin/bash
#
# bootstrap installs tools

export HOME=/home/snape
export DOT=$HOME/.dotfiles
export CONFIG=$HOME/.config
export RICE=$HOME/.rice

. $DOT/utils/print_functions.sh

cd "$(dirname "$0")/.."
DOTFILES_ROOT=$(pwd -P)

set -e

setup_tools () {
  # by default i"m sourcing for arch packages.
  # in future if u go use another os dismember that
  # to setup_tools_arch...
  info "Installing packages"
  declare -a packages=("curl" "wget" "git" "zsh"
  "archlinux-keyring" "autoconf" "automake" "binutils" "bison"
  "debugedit" "fakeroot" "file" "findutils" "flex" "gawk"
  "gcc" "gettext" "grep" "groff" "gzip" "libtool" "m4" "make"
  "pacman" "patch" "pkgconf" "sed" "sudo" "texinfo" "which"
  "imagemagick" "ffmpeg" "less" "fzf" "net-tools" "zoxide")
  for package in "${packages[@]}"
  do
    if ! pacman -Qi $package > /dev/null 2>&1 ; then
      sudo pacman -S $package --noconfirm > /dev/null 2>&1
      success "$package installed"
    else
      info "$package already installed"
    fi
  done
  success "Packages Success"
}

link_file () {
  local src=$1 dst=$2

  local overwrite= backup= skip=
  local action=

  if [ -f "$dst" -o -d "$dst" -o -L "$dst" ]
  then

    if [ "$overwrite_all" == "false" ] && [ "$backup_all" == "false" ] && [ "$skip_all" == "false" ]
    then

      local currentSrc="$(readlink $dst)"

      if [ "$currentSrc" == "$src" ]
      then

        skip=true;

      else

        user "File already exists: $dst ($(basename "$src")), what do you want to do?\n\
        [s]kip, [S]kip all, [o]verwrite, [O]verwrite all, [b]ackup, [B]ackup all?"
        read -n 1 action

        case "$action" in
          o )
            overwrite=true;;
          O )
            overwrite_all=true;;
          b )
            backup=true;;
          B )
            backup_all=true;;
          s )
            skip=true;;
          S )
            skip_all=true;;
          * )
            ;;
        esac

      fi

    fi

    overwrite=${overwrite:-$overwrite_all}
    backup=${backup:-$backup_all}
    skip=${skip:-$skip_all}

    if [ "$overwrite" == "true" ]
    then
      rm -rf "$dst"
      success "removed $dst"
    fi

    if [ "$backup" == "true" ]
    then
      mv "$dst" "${dst}.backup"
      success "moved $dst to ${dst}.backup"
    fi

    if [ "$skip" == "true" ]
    then
      info "skipped $src"
    fi
  fi

  if [ "$skip" != "true" ]  # "false" or empty
  then
    ln -s "$1" "$2"
    success "linked $1 to $2"
  fi
}

install_dotfiles () {
  info 'installing dotfiles'

  local overwrite_all=false backup_all=false skip_all=false

  for src in $(find -H "$DOTFILES_ROOT" -maxdepth 2 -name '*.symlink' -not -path '*.git*')
  do
    dst="$HOME/.$(basename "${src%.*}")"
    link_file "$src" "$dst"
  done
}


success "Setup Started"
setup_tools
install_dotfiles
success "Setup Completed"

echo ""
info "Starting Installations"
/bin/bash $DOTFILES_ROOT/scripts/install
success "Installations Completed"
